In [1]:
import numpy as np

In [18]:
import pandas as pd

In [3]:
np.random.rand(5,5)

array([[0.0376626 , 0.9823693 , 0.19168653, 0.32778605, 0.91863847],
       [0.41513179, 0.19337901, 0.02850977, 0.70256332, 0.98040571],
       [0.16935858, 0.98897948, 0.57186614, 0.39806765, 0.57761375],
       [0.36204713, 0.09014121, 0.40395195, 0.97872765, 0.81199638],
       [0.84671229, 0.93657727, 0.44190062, 0.22270251, 0.52083696]])

In [4]:
np.random.randn(5,5)

array([[ 0.81921492, -0.56339079, -0.74578315,  0.62938011,  0.17806552],
       [-0.08835085, -0.14668361,  1.07614728,  0.88471287, -1.26317793],
       [-0.81332577,  0.12405369, -0.45448982,  0.56714058, -0.39173234],
       [ 0.58480823,  0.09273573, -1.11454138,  1.18380403,  0.58914509],
       [-0.49138738,  2.39017251,  1.1525477 , -0.25721296,  0.27109351]])

In [6]:
arr = np.arange(1,11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr **.05

array([1.        , 1.03526492, 1.05646731, 1.07177346, 1.08379839,
       1.09372355, 1.10218603, 1.10956947, 1.11612317, 1.12201845])

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat.sum()

325

In [13]:
mat.sum(1)

array([ 15,  40,  65,  90, 115])

In [15]:
mat.sum(0)

array([55, 60, 65, 70, 75])

In [20]:
np.random.seed(101)

from numpy.random import randn

In [21]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [22]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [23]:
df[['Z','X']]

Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [27]:
df['Z','X']

KeyError: ('Z', 'X')