# numpy arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#getting 10 evenpoint numbers between zero to five
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.38334905, 0.7021639 , 0.51572295, 0.03753249, 0.83487116])

In [20]:
np.random.randn(5,5)

array([[ 1.93572259,  0.71535257,  0.12318358,  0.33698469,  0.99521765],
       [-0.21269621,  0.47615323, -0.9965875 , -0.20475793, -0.42376336],
       [ 0.08520482, -1.29504452, -0.72603327, -1.20035853,  2.36605898],
       [ 0.35945652,  0.50406217,  0.2405448 , -0.21753566, -1.65954351],
       [-1.56915419, -1.31969849,  2.24251676,  0.4152788 ,  1.42321331]])

In [21]:
np.random.randint(1,100)

63

In [22]:
#pick 10 random integers between 1 to 100
np.random.randint(1,100,10)

array([23, 74, 42, 80, 43, 20, 64, 42, 56, 17])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr

array([35, 38,  5, 11, 48,  5, 46, 10,  6, 38])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

48

In [29]:
ranarr.min()

5

In [30]:
ranarr

array([35, 38,  5, 11, 48,  5, 46, 10,  6, 38])

In [31]:
ranarr.argmax()

4

In [32]:
ranarr.argmin()

2

In [33]:
arr = arr.reshape(5,5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [37]:
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

2

# Numpy indexing and selection

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5]=100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:

slice_of_arr = arr[0:6]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]=99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
#as seen we had taken array slice from whole then applied changes on it but it also affects the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
#to overcome that thing we need to make a copy of array first

In [58]:
arr_copy = arr.copy()

In [59]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:]=100

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [63]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr2d[0,0]

5

In [65]:
arr2d[0]

array([ 5, 10, 15])

In [67]:
arr2d[1][1]

25

In [69]:
arr2d[1,1]

25

In [70]:
#arr2d[start k do,one se onward]
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr > 5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [95]:
arr[arr<3]

array([1, 2])

In [96]:
arr2d = np.arange(50).reshape(5,10)

In [97]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [98]:
arr2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [99]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# numpy operations

In [100]:
arr = np.arange(0,11)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [107]:
1/0

ZeroDivisionError: division by zero

In [113]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr/arr

C:\Users\Noman\AppData\Local\Temp/ipykernel_6372/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
1/arr

C:\Users\Noman\AppData\Local\Temp/ipykernel_6372/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [119]:
#taking square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [120]:
#attaching exponents
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [121]:
np.max(arr)

10

In [122]:
arr.max()

10

In [124]:
#taking sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [125]:
np.log(arr)

C:\Users\Noman\AppData\Local\Temp/ipykernel_6372/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [126]:
#end of notebook